---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Principal Component Analysis

```{r}
USArrests
dimnames(USArrests)
apply(USArrests, 2, mean)
apply(USArrests, 2, var)

```
```{r}
pca.out = prcomp(USArrests, scale = TRUE)
pca.out
names(pca.out)
biplot(pca.out, scale=0, cex = 0.5)
```
```{r}
PCbiplot <- function(PC, x="PC1", y="PC2") {
    # PC being a prcomp object
    data <- data.frame(obsnames=row.names(PC$x), PC$x)
    plot <- ggplot(data, aes_string(x=x, y=y)) + geom_text(alpha=.4, size=3, aes(label=obsnames))
    plot <- plot + geom_hline(aes(0), size=.2) + geom_vline(aes(0), size=.2)
    datapc <- data.frame(varnames=rownames(PC$rotation), PC$rotation)
    mult <- min(
        (max(data[,y]) - min(data[,y])/(max(datapc[,y])-min(datapc[,y]))),
        (max(data[,x]) - min(data[,x])/(max(datapc[,x])-min(datapc[,x])))
        )
    datapc <- transform(datapc,
            v1 = .7 * mult * (get(x)),
            v2 = .7 * mult * (get(y))
            )
    plot <- plot + coord_equal() + geom_text(data=datapc, aes(x=v1, y=v2, label=varnames), size = 5, vjust=1, color="red")
    plot <- plot + geom_segment(data=datapc, aes(x=0, y=0, xend=v1, yend=v2), arrow=arrow(length=unit(0.2,"cm")), alpha=0.75, color="red")
    plot
}

library(ggplot2)
fit <- prcomp(USArrests, scale=TRUE)
PCbiplot(fit)
```
K-means clustering
```{r}
set.seed(101)
x = matrix(rnorm(100*2),100,2)
plot(x)
xmean = matrix(rnorm(8, sd =4), 4,2)
which = sample(1:4, 100, replace = TRUE)
x = x +xmean[which,]
plot(x, col = which, pch =19)


```
```{r}
km.out = kmeans(x, 4, nstart = 15)
km.out
plot(x, col = km.out$cluster, cex = 2, pch =1, lwd=2)
points(x, col = which, pch = 19)
points(x, col = c(4,3,2,1)[which], pch =19)
```
#Hierarchial Clustering

```{r}
hc.complete = hclust(dist(x), method = "complete")
plot(hc.complete)
hc.single = hclust(dist(x), method = "single")
plot(hc.single)
hc.average = hclust(dist(x), method = "average")
plot(hc.average)

```
```{r}
hc.cut = cutree(hc.complete,4)
table(hc.cut, which)
table(hc.cut, km.out$cluster)
```

```{r}
plot(hc.complete, labels = which)
```

