---
title: "Chap_8-Tree based models"
author: "Aakash Sahu"
date: "April 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Decision Trees
Carseats data



```{r}
library(ISLR)
library(tree)
attach(Carseats)
hist(Sales)
High = ifelse(Sales <= 8, "No", "Yes")
Carseats = data.frame(Carseats, High)
View(Carseats)

```

```{r}
library(ggplot2)
ggplot(Carseats) +
  geom_histogram(aes(Sales), bins = 50)

ggplot(Carseats) +
  geom_freqpoly(aes(Sales))
```


```{r}
tree.carseats = tree(High ~ .-Sales, data = Carseats)
summary(tree.carseats)
plot(tree.carseats)
text(tree.carseats, pretty =0)
```
```{r}
tree.carseats
```
Creating tree with training and test set

```{r}
set.seed(1011)
train = sample(1:nrow(Carseats), 250)
tree.carseats = tree(High ~ . - Sales, Carseats, subset = train)
#tree.carseats
plot(tree.carseats);text(tree.carseats, pretty =0)
tree.pred = predict(tree.carseats, Carseats[-train,], type = "class")
with(Carseats[-train,], table(tree.pred, High))
(74+34)/150
```
Choosing tree size through cross validation


```{r}
cv.carseats = cv.tree(tree.carseats, FUN = prune.misclass)
cv.carseats
summary(cv.carseats)
plot(cv.carseats)
prune.carseats = prune.misclass(tree.carseats, best = 13)
plot(prune.carseats);text(prune.carseats, pretty =0)
```
Evaluating on test data

```{r}
tree.pred = predict(prune.carseats, Carseats[-train,], type = "class")
with(Carseats[-train,], table(tree.pred, High))
(72+32)/150
```

